import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '../components/organisms/Sidebar'
import Hero from '../components/organisms/Hero'
import styles from '../styles/Home.module.scss'
import ContactSection from '../components/organisms/ContactSection'
import ExperienciesSection from "../components/organisms/ExperienciesSection"
import TechnologyIconsSection from '../components/organisms/TechnologyIconsSection'
import ProfileSection from '../components/organisms/ProfileSection'
import LanguageSelector from "../components/atoms/LanguageSelector"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LanguageSelector />
        <Sidebar/>
        <Hero/>
        <ProfileSection/>
        <TechnologyIconsSection />
        <ExperienciesSection />
        <ContactSection />
      </main>
    </div>
  )
}

export default Home
