import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '../components/organisms/Sidebar'
import Hero from '../components/organisms/Hero'
import styles from '../styles/Home.module.scss'
import '../styles/globals.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar/>
        <Hero/>
      </main>
    </div>
  )
}

export default Home
